(* Function Data

Calling Conventions
===================

Stack Usage
-----------
Arguments passed on the stack. Local variables alloocated on the stack.

Stack Frames (Stack calling convention):
  <Start of previous stack frame>   <- Original IX
  <End of local vars, pushes, etc>  <- Original SP
  <Arguments pushed onto stack>
  Return-addr         <- From call to function
  Prev-IX             <- From previous stack frame
  <Local variables>   <- New IX points here
  <End of local vars> <- New SP



Parameter passing

Calling Conventions: REGISTER, CALL, RST

|-----------|-----------------------------|
|  Access   | Data Type (of Parameter)    |
| Specifier | Register    | Pointered     |
|-----------|-------------|---------------|
| (value)   | Value       | Ref (copy)[1] |
|-----------|-------------|---------------|
| VAR       | Value       | Ref           |
|-----------|-------------|---------------|
| CONST     | Value       | Ref           |
|-----------|-------------|---------------|
| OUT       | Value       | Ref[2]        |
|-----------|-------------|---------------|
| Result    | Value       | Ref[2]        |
|-----------|-------------|---------------|
[1] - Hidden copy performed by caller into callees static variables
[2] - Reference passed in by caller in registers

Calling Conventions: STACK

|-----------|-----------------------------|
|  Access   | Data Type (of Parameter)    |
| Specifier | Register    | Pointered     |
|-----------|-------------|---------------|
| (value)   | Value       | Ref (copy)[3] |
|-----------|-------------|---------------|
| VAR       | Ref         | Ref           |
|-----------|-------------|---------------|
| CONST     | Value       | Ref           |
|-----------|-------------|---------------|
| OUT       | Ref         | Ref[4]        |
|-----------|-------------|---------------|
| Result    | Value[5]    | Ref[4]        |
|-----------|-------------|---------------|
[3] - Hidden copy performed by caller into stack space. (Note limits on stack frame size).
[4] - References passed in by caller on stack
[5] - Value returned in a register
*)

unit Def.Functions;

interface
uses Classes, Generics.Collections, SysUtils,
  Def.Operators, Def.VarTypes, Def.Consts, Def.Variables, Def.UserTypes, Def.ScopesEX,
  Z80.Hardware;

//Maximum number of parameters which can be specified for a routine, including results
const MaxFunctionParams = 10;

type
  TFuncFlag = (
    ffForward,    //This is a forward declaration
    ffOverloaded  //Overloaded if multiple functions with the same name, but different parameters
                  //(Currently no plans to support overloading)
     );
  TFuncFlagSet = set of TFuncFlag;

  TCallingConvention = (
    ccUnknown,    //I.e. not yet assigned/parser error
    ccIntrinsic,  //No call needed! Generated by code generator
                  //Not available for user defined functions
    ccStack,      //Both parameters and variables allocated to an IX based stack frame
    ccRegister,   //Parameters allocated to registers (if possible), otherwise
                  //spilled to static (global) variables
    ccCall,       //A call to external code (at fixed address), otherwise as Register
                  //Takes a parameter which is an address constant
    ccRST,        //As ccCode but for routines dispatched via Z80 RST instructions
    ccExtern      //As ccCall but to calls a label. Takes a parameter which is a
                  //string constant. The string must be a label declared in an included
                  //assemblyfile
    );

  ECallingConvention = class(Exception)
    constructor Create;reintroduce;
  end;

//This probably ought to be a compiler option. TODO
const
//  DefaultCallingConvention = ccStackFrame;
  DefaultExternCallingConvention = ccRegister;

type
  TParamAccess = (
    //Function parameters:
    paNone,   //No such parameter
    paVal,    //Original value is not modified
    paVar,    //Original value will be modified by the function
    paConst,  //Original value will not be modified by the function
    paOut,    //No value is passed in, a value will be returned
    paResult);  //Is a result

  //Flags for intrinsic parameters
  TIntrinsicFlag = (
    ifToType        //If parameter's value is not vtTypeDef it will be converted
                    //to a vtTypeDef giving the type of the argument passed to it.
                    //Only valid where the intrinsic's result type is Parameterised.
                    //and the parameter is of type vtTypeDef.
    );
  TIntrinsicFlagSet = set of TIntrinsicFlag;

  TParamVariable = class;

  PParameter = ^TParameter;
  TParameter = record
    Access: TParamAccess; //Ignored for Intrinsics
    IsByRef: Boolean;     //True if the parameter is passed by reference. The value
                          //will depend on the Access type, the Calling Convention
                          //and the type of the parameter (ie whether it is a Pointered Type)
    Name: String;
    Variable: TParamVariable; //The variable created for this parameter

    Reg: TCPUReg;         //If the parameter is passed via a register, otherwise rNone
                          //Ignored for Intrinsics
    UserType: TUserType;  //Parameter type
    SuperType: TSuperType;  //Only for intrinsics. Only valid where VarType is vtUnknown.
    IntrinsicFlags: TIntrinsicFlagSet;  //Flags for Intrinsic params

    HasDefaultValue: Boolean;
    DefaultValue: TImmValue;   //If the parameter is optional.
                          //(only usable by Intrinsics at the moment)

    function VarType: TVarType;

    //Returns True if the param requires data to be passed the function (in registers)
    //when the function is called.
    //Val params require data to be passed in in registers for register types.
    //  For pointered types Val requires data to be copied into the functions local
    //  storage
    //VAR params require data to be passed in whether pass by value or pass by reference.
    //OUT and Result params will also require data to be passed in when being
    //passed by reference (ie. the pointer to the data).
    function PassDataIn: Boolean;
    //Returns True if the parameter requires a hidden copy of the arguments value
    //into the functions local storage. Used for Value arguments which are pointered types.
    function CopyDataIn: Boolean;
    //Returns True if the param requires data to be returned (in registers).
    //Params where data is return by reference require a pointer to be passed into
    //the function. The data is thus returned in memory at the referenced address
    //and no data is required to be returned by the function. Thus VAR, OUT and
    //Result params don't return any data when being passed by reference.
    function ReturnsData: Boolean;
    function ToString: String;
  end;

  //For variables which represent the parameters of a function
  TParamVariable = class(TVariable)
  private
    FParam: PParameter;
    FIsConst: Boolean;
    FIsParam: Boolean;
    FIsResult: Boolean;
  protected
    function GetIsConst: Boolean;override;
    function IncVersion: Integer;override;
  public
    //Parameters which have a value passed in will have VarVersion incremented
    constructor Create(const AName: String;AParam: PParameter; AOwner: TScope; AAddrMode: TAddrMode);

    //Returns the number of bytes to be allocated on the stack for storing this
    //variable as a parameter. Returns 0 if the variable's data is not passed via the
    //stack
    function GetStackBytesAsParam: Integer;
    function GetStackBytesAsLocal: Integer;override;

    function ToString: String;override;

    property Param: PParameter read FParam;
    //True if the variable is a function parameter (and NOT Result)
    property IsParam: Boolean read FIsParam;
    //True is the variable is the Result of a function
    property IsResult: Boolean read FIsResult;
  end;

  TParamArray = array[0..MaxFunctionParams] of TParameter;

  //For functions or procedures
  PFunction = ^TFunction;
  TFunction = record
    Name: String;
    Flags: TFuncFlagSet;    //Meta data about the function

    Preserves: TCPURegSet;  //Registers which are prserved
//    InRegs: TUsedRegSet;    //Registers used for inputs (parameters)
//    OutRegs: TUsedRegSet;   //Registers used for outputs (parameters and return values)

    Overloaded: Boolean;    //Overloaded if multiple functions with the same name, but different parameters
    IsExtern: Boolean;      //True if this is an Extern definition (i.e to external code - O/S etc)
    CallingConvention: TCallingConvention;
    ParamCount: Integer;
    ResultCount: Integer;   //Result count of zero = Procedure

    Op: TOperation;          //If this is an intrinsic (otherwise OpUnknown)
    CodeAddress: Word;      //If implemented in machine code at fixed address
    CodeLabel: String;      //For EXTERN directive - specifies the label of the assembly
                            //routine to call

    Params: TParamArray;    //Parameter data

    Comments: String;       //Freeform help etc text

    //Search the parameters of Func, from parameter 0 to Parameter LastIndex for
    //one matching the given ParamName
    function FindParam(ParamName: String; LastIndex: Integer): PParameter;
    //Finds the (first) Result parameter.
    //If none is found raises an exception
    function FindResult: PParameter;

    //Returns variable storage (specified by the calling convention)
    function GetParamAddrMode: TAddrMode;
    function GetLocalAddrMode: TAddrMode;

    //Returns the byte-size of arguments which are passed on the stack.
    //Includes the size of arguments /after/ ArgIndex (ie not including Arg[ArgIndex]).
    //Only includes data for Args which are passed as parameters on the stack
    //(ie. those which PassDataIn but not those which CopyDataIn)
    function GetParamByteSizeAfter(ArgIndex: Integer): Integer;

    //Returns the assembly instruction to call this function.
    //(Could be a CALL or an RST, or something fancier).
    function GetCallInstruction: String;

    function ToString: String;
  end;

type
  PFuncList = ^TFuncList;
  TFuncList = record
    Items: TList<PFunction>;

    procedure Initialise;
    procedure Clear;

    function Count: Integer;

    //Create a new function and return it
    function Add(const Name: String): PFunction;

    function FindByNameInScope(Name: String): PFunction;

    function ToString: String;
  end;

function CreateFuncList: PFuncList;

procedure SetCurrentFuncList(AFuncList: PFuncList);

//Find the given function
function FuncFindAllScopes(Name: String): PFunction;


type TFuncDirective = (
  dirUNKNOWN,
  dirFORWARD,
  dirCALL, dirRST, dirEXTERN,
  dirSTACK, dirREGISTER);

function IdentToFuncDirective(const Ident: String): TFuncDirective;

//Converts a string to an access specifier.
//If Ident is an access specifier returns True,
//if not returns False and Access returns paVal
function IdentToAccessSpecifier(const Ident: String;out Access: TParamAccess): Boolean;
//Extended version for meta data files which can accept ByRef suffix
function IdentToAccessSpecifierEX(const Ident: String;out Access: TParamAccess;
  out IsByRef: Boolean): Boolean;

//Returns True if a parameter under the given combination of calling convention,
//access specifier and type will be passed by reference, false otherwise
function IsPassByRef(CallingConvention: TCallingConvention; Access: TParamAccess;
  UserType: TUserType): Boolean;

function FunctionToFunctionHandle(Func: PFunction): TFunctionHandle;
function FunctionHandleToFunction(Handle: TFunctionHandle): PFunction;

//Current function list
var Funcs: PFuncList;

type TFuncs = class
  public
    //Adds a variable for a function parameter. To be called at the beginning of a function
    //declaration.
    //If Access is vsResult: Results are parsed as local variable to the function. The
    //Offset property for them will be initiated to -1, unless PassDataIn is True in
    //which case the address of tha data will be passed in the parameters and no data
    //will be returned in registers
    class function AddParamVariable(const AName: String;AParam: PParameter;
      AAddrMode: TAddrMode): TParamVariable;

    //--------------Finding/accessing

    //Finds the Result variable in the current Scope.
    //If there is no result variable, returns nil
    class function FindResult: TParamVariable;

    //-------------Code generation

    //Set the stack Offset values for local, stack based, variables.
    class procedure SetVariableOffsets;
    //Returns the number of bytes required on the stack for local variables in the
    //current scope.
    //NOTE: Result is considered a local variable, not a parameter.
    class function GetStackLocalsByteSize: Integer;
    //Returns number of bytes required for stack parameters by this scope.
    //Result is not a parameter.
    class function GetStackParamsByteSize: Integer;
  end;

implementation
uses Def.Scopes;

const
  //Offset from IX to the first parameter
  //IX+4... is parameters
  //IX+2 is return address
  //IX+0 is previous IX
  //< IX is local variables
  iStackOffsetForFirstParam = +4;

const ParamAccessStrings: array[low(TParamAccess)..high(TParamAccess)] of String =
  ('<None>', 'val','var','const','out','<result>');

{ ECallingConvention }

constructor ECallingConvention.Create;
begin
  inherited Create('Unknown calling convention');
end;

function CreateFuncList: PFuncList;
begin
  New(Result);
  Result.Initialise;
end;


procedure SetCurrentFuncList(AFuncList: PFuncList);
begin
  Funcs := AFuncList;
end;

function FuncFindAllScopes(Name: String): PFunction;
var IdentData: TIdentData;
begin
  IdentData := GetCurrentScope.SearchUpAll(Name);
  if IdentData.IdentType = itFunction then
    EXIT(IdentData.F);

  Result := nil;
end;

function IdentToFuncDirective(const Ident: String): TFuncDirective;
const DirectiveStrings: array[low(TFuncDirective)..high(TFuncDirective)] of String = (
  '',  //Placeholder for Unknown value
  'forward',
  'call','rst','extern',
  'stack','register');
begin
  for Result := low(TFuncDirective) to high(TFuncDirective) do
    if CompareText(DirectiveStrings[Result], Ident) = 0 then
      EXIT;

  Result := dirUnknown;
end;

//The keywords used in function declarations. Used when parsing source and when
//reconstructing function definitions (for help etc).
const AccessStrings: array[low(TParamAccess)..high(TParamAccess)] of String = (
  '',   //None
  '',   //Val doesn't have a keyword
  'var',
  'const',
  'out',
  '');  //Result doesn't have a keyword

function IdentToAccessSpecifier(const Ident: String;out Access: TParamAccess): Boolean;
var VA: TParamAccess;
begin
  for VA := low(TParamAccess) to high(TParamAccess) do
    if CompareText(AccessStrings[VA], Ident) = 0 then
    begin
      Access := VA;
      EXIT(True);
    end;

  Access := paVal;
  Result := False;
end;

function IdentToAccessSpecifierEX(const Ident: String;out Access: TParamAccess;
  out IsByRef: Boolean): Boolean;
var ByRef: String;
  NewIdent: String;
begin
  NewIdent := Ident;
  if Length(Ident) > 5 then
  begin
    ByRef := NewIdent.SubString(Length(Ident)-length('ByRef'));
    IsByRef := CompareText(ByRef, 'ByRef') = 0;
    if IsByRef then
      NewIdent := NewIdent.SubString(0, length(Ident)-Length('ByRef'));
  end
  else
    IsByRef := False;

  Result := IdentToAccessSpecifier(NewIdent, Access);
end;

function IsPassByRef(CallingConvention: TCallingConvention; Access: TParamAccess;
  UserType: TUserType): Boolean;
begin
  case CallingConvention of
    ccRegister, ccCALL, ccRST, ccExtern:
      Result := IsPointeredType(UserType);
    ccStack:
      Result := IsPointeredType(UserType) or
        //For these two we need to pass in the data address even for non-pointered types
        (Access in [paVar, paOut]);
  else
    raise ECallingConvention.Create;
  end;
end;

{ TParameter }

function TParameter.CopyDataIn: Boolean;
begin
  Result := IsByRef and (Access = paVal);
end;

function TParameter.PassDataIn: Boolean;
begin
  if IsByRef then
    Result := Access in [paVal, paVar, paConst, paOut, paResult]
  else
    Result := Access in [paVal, paVar, paConst];
end;

function TParameter.ReturnsData: Boolean;
begin
  Result := (Access in [paVar, paOut, paResult]) and not IsByRef;
end;

function TParameter.ToString: String;
begin
  Result := AccessStrings[Access];
  if Result <> '' then
    Result := Result + ' ';

  if Access <> paResult then
    Result := Result + Name;

  Result := Result + ': ';

  if Reg <> rNone then
  begin
    Result := Result + CPURegStrings[Reg];
    Result := Result + ' as ';
  end;

  if UserType <> nil then
    Result := Result + UserType.Description
  else
    Result := Result + SuperTypeToString(SuperType);

  if HasDefaultValue then
    Result := Result + ' = ' + DefaultValue.ToString;
end;

function TParameter.VarType: TVarType;
begin
  Result := UTToVT(UserType);
end;

{ TFunction }

function TFunction.FindParam(ParamName: String; LastIndex: Integer): PParameter;
var I: Integer;
begin
  for I := 0 to LastIndex do
    if I > MaxFunctionParams then
      EXIT(nil)
    else if CompareText(Params[I].Name, ParamName) = 0 then
      EXIT(@Params[I]);

  Result := nil;
end;

function TFunction.FindResult: PParameter;
var I: Integer;
begin
  for I := 0 to Length(Params)-1 do
    if Params[I].Access = paResult then
      EXIT(@Params[I]);

  Result := nil;
  Assert(False, 'Function result not found');
end;

function TFunction.GetCallInstruction: String;
begin
  case CallingConvention of
    ccCall: Result := 'call $' + IntToHex(CodeAddress, 4);
    ccRST:
      if CodeAddress > 7 then
        Result := 'rst $' + IntToHex(CodeAddress, 2)
      else
        Result := 'rst ' + IntToStr(CodeAddress);
    ccExtern: Result := 'call ' + CodeLabel;
    ccRegister, ccStack:
      Result := 'call _' + Name
  else
    raise ECallingConvention.Create;
  end;
end;

function TFunction.GetLocalAddrMode: TAddrMode;
begin
  case CallingConvention of
    ccRegister: Result := amStatic;
    ccStack: Result := amStack;
  else
    raise Exception.Create('Undefined Calling Convention');
  end;
end;

function TFunction.GetParamAddrMode: TAddrMode;
begin
  case CallingConvention of
    ccRegister:
      //Params are passed in registers. Storage will be alocated in global (static)
      //memory space but may (hopefully will) be optimised away into registers
      Result := amStatic;
    ccStack: Result := amStack;
  else
    raise Exception.Create('Undefined Calling Convention');
  end;
end;

function TFunction.GetParamByteSizeAfter(ArgIndex: Integer): Integer;
begin
  inc(ArgIndex);
  Result := 0;
  while ArgIndex < ParamCount + ResultCount do
  begin
    if Params[ArgIndex].PassDataIn then
      Result := Result + Params[ArgIndex].UserType.RegSize;
    Inc(ArgIndex);
  end;
end;

function TFunction.ToString: String;
var Param: Integer;
  Flag: TFuncFlag;
begin
  if ResultCount = 0 then
    Result := 'procedure'
  else
    Result := 'function';
  Result := Result + ' ' + Name;
  if ParamCount > 0 then
  begin
    Result := Result + '(';
    for Param := 0 to ParamCount-1 do
    begin
      if Param <> 0 then
        Result := Result + '; ';
      Result := Result + Params[Param].ToString;
    end;
    Result := Result + ')';
  end;
  if ResultCount <> 0 then
  begin
    for Param := ParamCount to ParamCount + ResultCount-1 do
    begin
      if Param > ParamCount then
        Result := Result + ';';
      Result := Result + Params[Param].ToString;
    end;
  end;

  Result := Result + ';';
  case CallingConvention of
    ccUnknown: Result := Result + ' UNKNOWN!!';
    ccIntrinsic: Result := Result + ' (Intrinsic)';
    ccCall, ccRST, ccExtern: Result := Result + GetCallInstruction + ';';
    ccStack: Result := Result + ' Stack;';
    ccRegister: Result := Result + ' Register;';
  else
    raise ECallingConvention.Create;
  end;

  for Flag in Flags do
  case Flag of
    ffForward: Result := Result + ' Forward (Unresolved!);';
    ffOverloaded: Result := Result + ' Overloaded;';
  else
    raise Exception.Create('Unknown function flag');
  end;
end;

function FunctionToFunctionHandle(Func: PFunction): TFunctionHandle;
begin
  Result := TFunctionHandle(Func);
end;

function FunctionHandleToFunction(Handle: TFunctionHandle): PFunction;
begin
  Result := PFunction(Handle);
end;

{ TFuncList }

function TFuncList.Count: Integer;
begin
  Result := Items.Count;
end;

function TFuncList.FindByNameInScope(Name: String): PFunction;
begin
  for Result in Items do
    if CompareText(Result.Name, Name) = 0 then
      EXIT;

  Result := nil;
end;

function TFuncList.Add(const Name: String): PFunction;
var I: Integer;
begin
  New(Result);
  Items.Add(Result);
  Result.Name := Name;
  Result.Flags := [];
  Result.Preserves := [];
//  Result.InRegs := [];
//  Result.OutRegs := [];
  Result.IsExtern := False;
  Result.CallingConvention := ccUnknown;
  Result.ParamCount := 0;
  Result.ResultCount := 0;
  Result.Op := OpUnknown;
  Result.CodeAddress := 0;

  for I := 0 to MaxFunctionParams do
  begin
    Result.Params[I].Name := '';
    Result.Params[I].Variable := nil;
    Result.Params[I].Reg := rNone;
    Result.Params[I].UserType := nil;
//    Result.Params[I].VarTypes := [];
    Result.Params[I].Access := paNone;
    Result.Params[I].HasDefaultValue := False;
    Result.Params[I].IsByRef := False;
//    Result.Params[I].DefaultValue := 0;
  end;
end;

procedure TFuncList.Clear;
var F: PFunction;
begin
  for F in Items do
    Dispose(F);

  Items.Free;
  Items := nil;
end;

procedure TFuncList.Initialise;
begin
  Items := TList<PFunction>.Create;
end;

function TFuncList.ToString: String;
var Func: PFunction;
begin
  Result := '';
  for Func in Items do
    Result := Result + Func.ToString + #13#10;
end;

{ TFuncs }

class function TFuncs.AddParamVariable(const AName: String;AParam: PParameter;
  AAddrMode: TAddrMode): TParamVariable;
var Scope: TScope;
begin
  Scope := GetCurrentScope.BlockScope;
  Assert(GetCurrentScope.SearchUpLocal(AParam.Name).IdentType = itUnknown);

  Result := TParamVariable.Create(AName, AParam, Scope, AAddrMode);
  Scope.Add(Result);
end;

class function TFuncs.FindResult: TParamVariable;
begin
  Result := GetCurrentScope.FunctionScope.SearchUpLocal<TParamVariable>(
    function(Item: TParamVariable): TParamVariable
    begin
      if Item.IsResult then
        Result := Item
      else
        Result := nil;
    end);
end;

class function TFuncs.GetStackLocalsByteSize: Integer;
var Size: Integer;
begin
  Size := 0;
  GetCurrentScope.FunctionScope.EachDown<TVariable>(
    procedure(V: TVariable)
    begin
      Size := Size + V.GetStackBytesAsLocal;
    end);

  Result := Size;
(*
    procedure(V: TVariable)
    begin
      if (V.Access in [vaLocal]) or (V is TParamVariable) and TParamVariable(V).IsResult then
        if V.RequiresStorage then
          case V.AddrMode of
            amStatic, amStaticRef: ;  //Ignore
            amStack: Size := Size + V.UserType.DataSize;
            amStackRef: Size := Size + GetVarTypeSize(vtPointer);
          else
            raise EAddrMode.Create;
          end;
    end);
*)
end;

class function TFuncs.GetStackParamsByteSize: Integer;
var Size: Integer;
begin
  Size := 0;
  GetCurrentScope.FunctionScope.EachDown<TParamVariable>(
    procedure(V: TParamVariable)
    begin
      Size := Size + V.GetStackBytesAsParam;
    end);

  Result := Size;
(*
var V: TVariable;
begin
  Result := 0;
  for V in Items do
    if V.IsParam then
      if V.RequiresStorage then
        case V.AddrMode of
          amStatic, amStaticRef: ;  //Ignore
          amStack: Result := Result + V.UserType.RegSize;
          amStackRef: Result := Result + GetVarTypeSize(vtPointer);
        else
          raise EAddrMode.Create;
        end;
*)
end;


class procedure TFuncs.SetVariableOffsets;

  procedure DoSetParamOffsets;
  var Offset: Integer;
  begin
    Offset := iStackOffsetForFirstParam;

    GetCurrentScope.FunctionScope.EachDown<TParamVariable>(
      procedure(V: TParamVariable)
      var Size: Integer;
      begin
        Assert(V.Offset = -1);

        //TODO: Ignore if optimised away
        case V.AddrMode of
          amStatic, amStaticRef: ;  //Ignore
          amStack, amStackRef:
          begin
            //Will retrun zero of no bytes to pass as parameter
            Size := V.GetStackBytesAsParam;
            if Size <> 0 then
            begin
              V.Offset := Offset;
              Offset := Offset + Size;
            end;
          end;
        else
          raise EAddrMode.Create;
        end;
      end);
  end;

  function DoSetLocalOffsets(Initial: Integer;PointeredTypes: Boolean): Integer;
  var Offset: Integer;
  begin
    Offset := Initial;

    GetCurrentScope.FunctionScope.EachDown<TVariable>(
      procedure(V: TVariable)
      var Size: Integer;
        Apply: Boolean;
      begin
        Apply := False;

        case V.AddrMode of
          amStatic, amStaticRef: ;  //Ignore
          amStack:
            Apply := IsPointeredVarType(V.VarType) = PointeredTypes;
          amStackRef:
            //If StackRef we need storage for a pointer
            Apply := not PointeredTypes;
        else
          raise EAddrMode.Create;
        end;

        if Apply then
        begin
          //Will return zero if no bytes to store as local data
          Size := V.GetStackBytesAsLocal;
          if Size <> 0 then
          begin
            Assert(V.Offset = -1);
            Offset := Offset - Size;
            V.Offset := Offset;
          end;
        end;
      end);

    Result := Offset;
  end;

var Offset: Integer;
begin
  DoSetParamOffsets;

  //Offsets for Register types and StackRef addr mode
  Offset := DoSetLocalOffsets(0, False);
  //Generate offsets for Pointered Types
  //They need to be stored beyond other variables due to limits in index register
  //offset ranges. (They will be accessed using explicit additions to/from stack base)
  DoSetLocalOffsets(Offset, True);
end;

{ TParamVariable }

constructor TParamVariable.Create(const AName: String; AParam: PParameter; AOwner: TScope;
  AAddrMode: TAddrMode);
begin
  inherited Create(AName, AOwner, AParam.UserType, AAddrMode);
  FParam := AParam;
  FIsResult := Param.Access = paResult;
  FIsParam := Param.PassDataIn or not IsResult;
  FIsConst := Param.Access = paConst;
  //Inc the variables write count to indicate it's been assigned a value by the caller
  if not (Param.Access in [paOut, paResult]) then
    inherited IncVersion;

  Offset := -1;
end;

function TParamVariable.GetIsConst: Boolean;
begin
  Result := FIsConst;
end;

function TParamVariable.GetStackBytesAsLocal: Integer;
begin
  //Result variable requires storage as if it was a local variable...
  //...unless it's amStackRef, in which case a data address is passed in.
  if IsResult and (AddrMode <> amStackRef) then
    Result := inherited
  else
    Result := 0;
end;

function TParamVariable.GetStackBytesAsParam: Integer;
begin
  if IsResult and not Param.PassDataIn then
    //We use a varref passed into the function
    Result := 0
  else
  if IsParam then //Redundant to the above??
    case AddrMode of
      amStatic, amStaticRef: Result := 0;  //Not passed on stack
      amStack:  //Passed as data
        Result := UserType.DataSize;
      amStackRef: //Passed as pointer
        Result := GetVarTypeSize(vtPointer);
    else
      raise EAddrMode.Create;
    end
  else
    Result := 0;
end;

function TParamVariable.IncVersion: Integer;
begin
  Assert(not IsConst);
  Result := inherited;
end;

function TParamVariable.ToString: String;
begin
  Result := '(Param) <' +ParamAccessStrings[Param.Access] + '> ' + Name + ': ' + Description;
end;

initialization
  Funcs := nil;
finalization
end.
